# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/HP/Desktop/RCS/HW02/EbraahimianHW2codesign/EbraahimianHW2codesign.srcs/sources_1/bd/PL_phase/ip/PL_phase_processing_system7_0_0/PL_phase_processing_system7_0_0.xci
# IP: The module: 'PL_phase_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/RCS/HW02/EbraahimianHW2codesign/EbraahimianHW2codesign.gen/sources_1/bd/PL_phase/ip/PL_phase_processing_system7_0_0/PL_phase_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_phase_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/HP/Desktop/RCS/HW02/EbraahimianHW2codesign/EbraahimianHW2codesign.srcs/sources_1/bd/PL_phase/ip/PL_phase_processing_system7_0_0/PL_phase_processing_system7_0_0.xci
# IP: The module: 'PL_phase_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/RCS/HW02/EbraahimianHW2codesign/EbraahimianHW2codesign.gen/sources_1/bd/PL_phase/ip/PL_phase_processing_system7_0_0/PL_phase_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_phase_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
