# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/term5/vivado projects/CORDIC/CORDIC.srcs/sources_1/bd/PL/ip/PL_c_addsub_0_0/PL_c_addsub_0_0.xci
# IP: The module: 'PL_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/term5/vivado projects/CORDIC/CORDIC.gen/sources_1/bd/PL/ip/PL_c_addsub_0_0/PL_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/term5/vivado projects/CORDIC/CORDIC.srcs/sources_1/bd/PL/ip/PL_c_addsub_0_0/PL_c_addsub_0_0.xci
# IP: The module: 'PL_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/term5/vivado projects/CORDIC/CORDIC.gen/sources_1/bd/PL/ip/PL_c_addsub_0_0/PL_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
