# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PL_phase/PL_phase.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase || ORIG_REF_NAME==PL_phase} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_processing_system7_0_0/PL_phase_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_processing_system7_0_0 || ORIG_REF_NAME==PL_phase_processing_system7_0_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_axi_gpio_0_0/PL_phase_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_axi_gpio_0_0 || ORIG_REF_NAME==PL_phase_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_ps7_0_axi_periph_0/PL_phase_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_ps7_0_axi_periph_0 || ORIG_REF_NAME==PL_phase_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_rst_ps7_0_50M_0/PL_phase_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_rst_ps7_0_50M_0 || ORIG_REF_NAME==PL_phase_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_blk_mem_gen_0_0/PL_phase_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_blk_mem_gen_0_0 || ORIG_REF_NAME==PL_phase_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_c_shift_ram_0_0/PL_phase_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_c_shift_ram_0_0 || ORIG_REF_NAME==PL_phase_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_c_shift_ram_0_1/PL_phase_c_shift_ram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_c_shift_ram_0_1 || ORIG_REF_NAME==PL_phase_c_shift_ram_0_1} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_c_shift_ram_0_2/PL_phase_c_shift_ram_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_c_shift_ram_0_2 || ORIG_REF_NAME==PL_phase_c_shift_ram_0_2} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_blk_mem_gen_0_1/PL_phase_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_blk_mem_gen_0_1 || ORIG_REF_NAME==PL_phase_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_c_addsub_0_0/PL_phase_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_c_addsub_0_0 || ORIG_REF_NAME==PL_phase_c_addsub_0_0} -quiet] -quiet

# IP: bd/PL_phase/ip/PL_phase_auto_pc_0/PL_phase_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_phase_auto_pc_0 || ORIG_REF_NAME==PL_phase_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/HP/Desktop/RCS/HW02/EbraahimianHW2codesign/EbraahimianHW2codesign.gen/sources_1/bd/PL_phase/PL_phase_ooc.xdc
