# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PL/PL.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL || ORIG_REF_NAME==PL} -quiet] -quiet

# IP: bd/PL/ip/PL_processing_system7_0_0/PL_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_processing_system7_0_0 || ORIG_REF_NAME==PL_processing_system7_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_axi_gpio_0_0/PL_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_axi_gpio_0_0 || ORIG_REF_NAME==PL_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_auto_pc_0/PL_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_auto_pc_0 || ORIG_REF_NAME==PL_auto_pc_0} -quiet] -quiet

# IP: bd/PL/ip/PL_ps7_0_axi_periph_0/PL_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_ps7_0_axi_periph_0 || ORIG_REF_NAME==PL_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PL/ip/PL_rst_ps7_0_50M_0/PL_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_rst_ps7_0_50M_0 || ORIG_REF_NAME==PL_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PL/ip/PL_cordic_0_0/PL_cordic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_cordic_0_0 || ORIG_REF_NAME==PL_cordic_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_mult_gen_0_0/PL_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_mult_gen_0_0 || ORIG_REF_NAME==PL_mult_gen_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_xlconstant_0_0/PL_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_xlconstant_0_0 || ORIG_REF_NAME==PL_xlconstant_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_xbip_multadd_0_0/PL_xbip_multadd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_xbip_multadd_0_0 || ORIG_REF_NAME==PL_xbip_multadd_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_c_addsub_0_0/PL_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_c_addsub_0_0 || ORIG_REF_NAME==PL_c_addsub_0_0} -quiet] -quiet

# IP: bd/PL/ip/PL_cordic_1_0/PL_cordic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PL_cordic_1_0 || ORIG_REF_NAME==PL_cordic_1_0} -quiet] -quiet

# XDC: g:/term5/vivado projects/CORDIC/CORDIC.gen/sources_1/bd/PL/PL_ooc.xdc
